language: r
warnings_are_errors: false
cache: packages

r_github_packages: FlorianSchwendinger/pdfminer

branches:
  only:
    - "master"

r:
  - oldrel
  - release
  - devel 

os:
  - linux
  #- osx devel and release fails mysteriously on osx, have to look into this...
