
html_vignette:
	R -e 'rmarkdown::render("Usage.Rmd", clean = FALSE, output_format = c("html_document"))'

pdf_vignette:
	R -e 'rmarkdown::render("Usage.Rmd", clean = FALSE, output_format = c("pdf_document"))'

